services:
  web:
    build: ./
    restart: unless-stopped
    volumes:
      - ../oasis-setup-config.json:/app/oasis-setup-config.json:z
      - ../wireguard:/app/wireguard:z
    ports:
      - "4040:4040"
